import type { languages } from "monaco-editor"

export const pineLanguage: languages.IMonarchLanguage = {
  defaultToken: "",
  tokenPostfix: ".pine",
  keywords: [
    "and", "or", "not", "if", "else", "for", "while", "switch",
    "var", "varip", "true", "false", "na", "bool", "int", "float",
    "string", "color", "line", "label", "table", "box",
    "input", "plot", "hline", "fill", "bgcolor", "plotshape",
    "alertcondition", "strategy", "indicator", "library",
    "export", "method", "type", "enum",
  ],
  builtinFunctions: [
    "ta.sma", "ta.ema", "ta.rsi", "ta.macd", "ta.bb", "ta.supertrend",
    "ta.atr", "ta.vwap", "ta.vwma", "ta.wma", "ta.hma", "ta.alma",
    "ta.stoch", "ta.stochrsi", "ta.crossover", "ta.crossunder",
    "ta.cross", "ta.highest", "ta.lowest", "ta.sum", "ta.avg",
    "ta.median", "ta.mode", "ta.stdev", "ta.variance", "ta.correlation",
    "ta.linreg", "ta.tr", "ta.trueRange", "ta.roc", "ta.mom",
    "ta.change", "ta.barssince", "ta.valuewhen", "ta.pivothigh",
    "ta.pivotlow", "ta.rising", "ta.falling",
    "math.abs", "math.ceil", "math.floor", "math.round", "math.max",
    "math.min", "math.pow", "math.sqrt", "math.log", "math.exp",
    "math.sin", "math.cos", "math.tan", "math.avg",
    "strategy.entry", "strategy.exit", "strategy.close",
    "strategy.order", "strategy.cancel", "strategy.close_all",
    "array.new", "array.push", "array.pop", "array.get", "array.set",
    "array.size", "array.clear", "array.includes", "array.slice",
    "matrix.new", "matrix.rows", "matrix.columns", "matrix.get", "matrix.set",
    "color.new", "color.rgb", "color.gray",
    "line.new", "line.set_xy1", "line.set_xy2", "line.set_color",
    "label.new", "label.set_xy", "label.set_text", "label.set_color",
    "table.new", "table.cell", "table.merge_cells",
    "box.new", "box.set_border_color", "box.set_bgcolor",
    "request.security", "request.dividends", "request.splits",
    "syminfo.ticker", "syminfo.tickerid", "syminfo.currency",
    "syminfo.description", "syminfo.type", "syminfo.session",
    "timeframe.period", "timeframe.is_seconds", "timeframe.multiplier",
    "barstate.isconfirmed", "barstate.isnew", "barstate.isfirst",
    "strategy.initial_capital", "strategy.equity", "strategy.position_size",
    "strategy.position_avg_price", "strategy.profit", "strategy.loss",
    "strategy.wintrades", "strategy.losstrades",
  ],
  typeKeywords: ["open", "high", "low", "close", "volume", "hl2", "hlc3", "ohlc4", "time"],
  operators: [
    "=", ">", "<", "!", "~", "?", ":", "==", "<=", ">=", "!=",
    "&&", "||", "++", "--", "+", "-", "*", "/", "&", "|", "^", "%",
    "<<", ">>", ">>>", "+=", "-=", "*=", "/=", "&=", "|=", "^=", "%=",
    "<<=", ">>=", ">>>=",
  ],
  symbols: /[=><!:~?&|+\-*/^%]+/,
  escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
  tokenizer: {
    root: [
      [/[a-z_$][\w$]*/, { cases: { "@typeKeywords": "keyword", "@keywords": "keyword", "@builtinFunctions": "type.identifier", "@default": "identifier" } }],
      { include: "@whitespace" },
      [/[{}()\[\]]/, "@brackets"],
      [/[<>](?!@symbols)/, "@brackets"],
      [/@symbols/, { cases: { "@operators": "operator", "@default": "" } }],
      [/\d*\.\d+([eE][\-+]?\d+)?/, "number.float"],
      [/\d+/, "number"],
      [/"/, { token: "string.quote", bracket: "@open", next: "@string" }],
      [/'/, { token: "string.quote", bracket: "@open", next: "@string_single" }],
    ],
    comment: [
      [/[^\/*]+/, "comment"],
      [/\*\//, "comment", "@pop"],
      [/[\/*]/, "comment"],
    ],
    string: [
      [/[^\\"]+/, "string"],
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/"/, { token: "string.quote", bracket: "@close", next: "@pop" }],
    ],
    string_single: [
      [/[^\\']+/, "string"],
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/'/, { token: "string.quote", bracket: "@close", next: "@pop" }],
    ],
    whitespace: [
      [/[ \t\r\n]+/, "white"],
      [/\/\/.*$/, "comment"],
      [/\/\*/, "comment", "@comment"],
    ],
  },
}
